
```{r}
  library(ggplot2)
```

```{r} 
  age_data <- readxl::read_xlsx("CSV_FILES/Public-Dataset-Daily-County-Age-Group.XLSX")      
  race_eth_data <- readxl::read_xlsx("CSV_FILES/Public-Dataset-RaceEthSex.XLSX")
  hospitalization_data <- readxl::read_xlsx("CSV_FILES/Public-Dataset-Daily-Case-Info.XLSX")
```

```{r}
  
  bedford_data <- age_data[which(age_data$COUNTY == "Bedford"),]                # extract bedford county data                     

  bedford_graph <- ggplot(bedford_data, aes(DATE, CASE_COUNT)) +                # create base plot
  geom_jitter(aes(col = AGE_GROUP), size = 1) +                                 # add jitter layer
  labs(col="Age Range") +                                                       # add label for age range
  xlab("Date") + ylab("Case Count") +                                           # add x and y labels
  ggtitle("Age Data for Bedford County") +                                      # add centered title
  theme(plot.title = element_text(hjust = 0.5))
  
  bedford_graph
  
  
  rutherford_data <- age_data[which(age_data$COUNTY == "Rutherford"),]
  
  rutherford_graph <- ggplot(rutherford_data, aes(DATE, CASE_COUNT)) +
  geom_jitter(aes(col = AGE_GROUP)) +
  labs(col="Age Range") + 
  xlab("Date") + ylab("Case Count") + 
    ggtitle("Age Data for Rutherford County") +
  theme(plot.title = element_text(hjust = 0.5))
  rutherford_graph
  
  
  davidson_data <- age_data[which(age_data$COUNTY == "Davidson"),]
  
  davidson_graph <- ggplot(davidson_data, aes(DATE, CASE_COUNT)) +
  geom_jitter(aes(col = AGE_GROUP)) + 
  labs(col="Age Range") + 
  xlab("Date") + ylab("Case Count") + ggtitle("Age Data for Davidson County") +
  theme(plot.title = element_text(hjust = 0.5))
  
  davidson_graph
```

```{r}
  race_data <- race_eth_data[which(race_eth_data$Category == "RACE"),]
  
  race_case_graph <- ggplot(race_data, aes(Date, Cat_CaseCount)) +
  geom_jitter(aes(col = CAT_DETAIL)) + 
  labs(col = "Race") + xlab("Date") + ylab("Case Count") +
  ggtitle("Race Case Count") +
  theme(plot.title = element_text(hjust = 0.5))
  
  race_case_graph
  
  
```

```{r}
  hospitalization_data <- na.omit(hospitalization_data)

  hos_graph <- ggplot(hospitalization_data, aes(DATE, NEW_HOSP)) +
  geom_line(color="red") +
  xlab("Date") + ylab("New Case Count") + 
  ggtitle("New Hospitalizations Count") +
  theme(plot.title = element_text(hjust = 0.5))
  
  hos_graph
  
  total_hos_graph <- ggplot(hospitalization_data, aes(DATE, TOTAL_HOSP)) +
  geom_line(color="red") + 
  xlab("Date") + ylab("Total Count") +
  ggtitle("Total Hospitalizations Count") +
  theme(plot.title = element_text(hjust = 0.5))
  
  total_hos_graph
```